version: "3.9"

services:
  backend-local:
    container_name: backend-local
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - default
    restart: always

networks:
  default:
